### ISSUE TITLE
script stops on 404

### ISSUE THREAD

**Issue by Bartzi** [hrantzsch/get-cn#7]
When encoutering a 404 the script should not die ;)

`get-cn-exe: StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Date","Mon, 29 Feb 2016 10:26:20 GMT"),("Server","PWS/8.1.20.25"),("Content-Length","0"),("Connection","close"),("X-Response-Body-Start",""),("X-Request-URL","GET http://2016.sina.com.cn:80/brazil/2016-02-27/doc-ifxpvysv4941923.shtml")] (CJ {expose = []})`

**Comment by hrantzsch** [comment]
Should be fixed now.
